#
# Profile
#

ezplatform.user_profile.change_password:
    path: /user/change-password
    defaults:
        _controller: 'EzPlatformUserBundle:PasswordChange:userPasswordChange'

ezplatform.user.forgot_password:
    path: /user/forgot-password
    defaults:
        _controller: 'EzPlatformUserBundle:PasswordReset:userForgotPassword'

ezplatform.user.forgot_password.login:
    path: /user/forgot-password/login
    defaults:
        _controller: 'EzPlatformUserBundle:PasswordReset:userForgotPasswordLogin'

ezplatform.user.reset_password:
    path: /user/reset-password/{hashKey}
    defaults:
        _controller: 'EzPlatformUserBundle:PasswordReset:userResetPassword'

ezplatform.user.register:
    path: /register
    defaults:
        _controller: "EzPlatformUserBundle:UserRegister:register"

ezplatform.user.register_confirmation:
    path: /register-confirm
    defaults:
        _controller: "EzPlatformUserBundle:UserRegister:registerConfirm"

ezplatform.user_settings.list:
    path: /user/settings/list/{page}
    defaults:
        _controller: 'EzPlatformUserBundle:UserSettings:list'
        page: 1
    requirements:
        page: \d+

ezplatform.user_settings.update:
    path: /user/settings/update/{identifier}
    defaults:
        _controller: 'EzPlatformUserBundle:UserSettings:update'
    requirements:
        identifier: .+
